#!/bin/bash -e

# https://www.reddit.com/r/emacs/comments/9aex0j/emacs_horrors_determining_if_the_server_is/
if ! ( emacsclient -c "$@" 2> /dev/null ); then
    echo "Couldn't start emacsclient"
    echo "Starting Emacs..."
    emacs --eval="(server-start)" "$@"
fi
